version: '3'
services:

  kanban-app:
    image: yomarajazmin/test_kanban_app
    container_name: kanban-app
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8080:8080

  kanban-ui:
    image: yomarajazmin/test_kanban_ui
    container_name: kanban-ui
    ports:
      - 4200:80
    links:
      - kanban-app
networks:
  default:
